/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.bpe;

/**
 * Remote interface for BPEProcess.
 * @author junglas
 * @created 13. Juli 2004
 */
public interface BPEProcess
   extends javax.ejb.EJBObject
{

   public de.objectcode.canyon.api.worklist.ProcessInstanceData getProcessInstance( java.lang.String processInstanceId )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessInstanceData getProcessInstanceReadOnly( java.lang.String processInstanceId )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData getProcessDefinition( java.lang.String processId )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData getProcessDefinition( java.lang.String processId,java.lang.String version )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.model.process.WorkflowProcess getProcess( java.lang.String processId,java.lang.String processVersion )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public int countProcesses(  )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public java.lang.String[] findMembers( java.lang.String processInstanceId,java.lang.String participantId,java.lang.String clientId )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData[] listActiveProcesses(  )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData[] listProcesses( int offset,int length )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData[] listCompactProcesses( int offset,int length )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessData[] listProcessData( int offset,int length )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.model.process.WorkflowProcess[] listProcesses(  )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessInstanceData createAndStartProcessInstance( de.objectcode.canyon.api.worklist.ProcessData processData )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessInstanceData createAndStartProcessInstance( java.lang.String userId,java.lang.String clientId,de.objectcode.canyon.api.worklist.ProcessData processData )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public void terminateProcessInstance( java.lang.String processInstanceId )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public void updateProcessInstance( de.objectcode.canyon.api.worklist.ProcessInstanceData processInstanceData )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessInstanceData[] listProcessInstances( java.lang.String processId,int offset,int length,boolean onlyOpen )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public de.objectcode.canyon.api.worklist.ProcessInstanceData[] listProcessInstances( java.lang.String processId,java.lang.String clientId,int offset,int length,boolean onlyOpen )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

}
