serialver -classpath dist/engine de.objectcode.canyon.model
serialver -classpath dist/engine de.objectcode.canyon.model.AbstractEnum
serialver -classpath dist/engine de.objectcode.canyon.model.activity
serialver -classpath dist/engine de.objectcode.canyon.model.activity.Activity
serialver -classpath dist/engine de.objectcode.canyon.model.application
serialver -classpath dist/engine de.objectcode.canyon.model.application.Application
serialver -classpath dist/engine de.objectcode.canyon.model.data
serialver -classpath dist/engine de.objectcode.canyon.model.data.ActualParameter
serialver -classpath dist/engine de.objectcode.canyon.model.participant
serialver -classpath dist/engine de.objectcode.canyon.model.participant.Participant
serialver -classpath dist/engine de.objectcode.canyon.model.process
serialver -classpath dist/engine de.objectcode.canyon.model.process.AccessLevel
serialver -classpath dist/engine de.objectcode.canyon.model.transition
serialver -classpath dist/engine de.objectcode.canyon.model.transition.Condition
serialver -classpath dist/engine de.objectcode.canyon.model.data.BasicType
serialver -classpath dist/engine de.objectcode.canyon.model.data.DataType
serialver -classpath dist/engine de.objectcode.canyon.model.data.DeclaredType
serialver -classpath dist/engine de.objectcode.canyon.model.data.EnumerationType
serialver -classpath dist/engine de.objectcode.canyon.model.data.EnumerationValue
serialver -classpath dist/engine de.objectcode.canyon.model.data.ExternalReference
serialver -classpath dist/engine de.objectcode.canyon.model.data.FormalParameter
serialver -classpath dist/engine de.objectcode.canyon.model.data.FormalParameterIndexComparator
serialver -classpath dist/engine de.objectcode.canyon.model.data.ParameterMode
serialver -classpath dist/engine de.objectcode.canyon.model.data.SchemaType
serialver -classpath dist/engine de.objectcode.canyon.model.data.TypeDeclaration
serialver -classpath dist/engine de.objectcode.canyon.model.BaseElement
serialver -classpath dist/engine de.objectcode.canyon.model.ExtendedAttribute
serialver -classpath dist/engine de.objectcode.canyon.model.ExternalPackage
serialver -classpath dist/engine de.objectcode.canyon.model.GraphConformance
serialver -classpath dist/engine de.objectcode.canyon.model.IValidatable
serialver -classpath dist/engine de.objectcode.canyon.model.PackageHeader
serialver -classpath dist/engine de.objectcode.canyon.model.PublicationStatus
serialver -classpath dist/engine de.objectcode.canyon.model.RedefinableHeader
serialver -classpath dist/engine de.objectcode.canyon.model.Script
serialver -classpath dist/engine de.objectcode.canyon.model.ValidationErrors
serialver -classpath dist/engine de.objectcode.canyon.model.WorkflowPackage
serialver -classpath dist/engine de.objectcode.canyon.model.activity.ActivitySet
serialver -classpath dist/engine de.objectcode.canyon.model.activity.AssignStrategy
serialver -classpath dist/engine de.objectcode.canyon.model.activity.AutomationMode
serialver -classpath dist/engine de.objectcode.canyon.model.activity.BlockActivity
serialver -classpath dist/engine de.objectcode.canyon.model.activity.CompletionStrategy
serialver -classpath dist/engine de.objectcode.canyon.model.activity.Deadline
serialver -classpath dist/engine de.objectcode.canyon.model.activity.ExecutionType
serialver -classpath dist/engine de.objectcode.canyon.model.activity.IActivityContainer
serialver -classpath dist/engine de.objectcode.canyon.model.activity.Implementation
serialver -classpath dist/engine de.objectcode.canyon.model.activity.InstantiationType
serialver -classpath dist/engine de.objectcode.canyon.model.activity.NoImplementation
serialver -classpath dist/engine de.objectcode.canyon.model.activity.Route
serialver -classpath dist/engine de.objectcode.canyon.model.activity.SimulationInformation
serialver -classpath dist/engine de.objectcode.canyon.model.activity.SubFlow
serialver -classpath dist/engine de.objectcode.canyon.model.activity.Tool
serialver -classpath dist/engine de.objectcode.canyon.model.activity.ToolSet
serialver -classpath dist/engine de.objectcode.canyon.model.activity.ToolType
serialver -classpath dist/engine de.objectcode.canyon.model.participant.ParticipantType
serialver -classpath dist/engine de.objectcode.canyon.model.process.DataField
serialver -classpath dist/engine de.objectcode.canyon.model.process.Duration
serialver -classpath dist/engine de.objectcode.canyon.model.process.DurationUnit
serialver -classpath dist/engine de.objectcode.canyon.model.process.ProcessHeader
serialver -classpath dist/engine de.objectcode.canyon.model.process.TimeEstimation
serialver -classpath dist/engine de.objectcode.canyon.model.process.WorkflowProcess
serialver -classpath dist/engine de.objectcode.canyon.model.transition.ConditionType
serialver -classpath dist/engine de.objectcode.canyon.model.transition.Join
serialver -classpath dist/engine de.objectcode.canyon.model.transition.JoinType
serialver -classpath dist/engine de.objectcode.canyon.model.transition.Split
serialver -classpath dist/engine de.objectcode.canyon.model.transition.SplitType
serialver -classpath dist/engine de.objectcode.canyon.model.transition.Transition
serialver -classpath dist/engine de.objectcode.canyon.model.transition.TransitionRef
serialver -classpath dist/engine de.objectcode.canyon.model.transition.TransitionRestriction
serialver -classpath dist/engine de.objectcode.canyon.model.transition.Xpression