/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.bpe.admin;

/**
 * Home interface for BPEProcessRepositoryAdmin.
 * @author junglas
 * @created 20. Juni 2003
 */
public interface BPEProcessRepositoryAdminHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/BPEProcessRepositoryAdmin";
   public static final String JNDI_NAME="de/objectcode/canyon/ejb/bpe/admin/ProcessRepositoryAdmin";

   public de.objectcode.canyon.api.bpe.admin.BPEProcessRepositoryAdmin create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
