/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.bpe.admin;

/**
 * Remote interface for BPEProcessRepositoryAdmin.
 * @author junglas
 * @created 20. Juni 2003
 */
public interface BPEProcessRepositoryAdmin
   extends javax.ejb.EJBObject
{

   public void createPackage( de.objectcode.canyon.model.WorkflowPackage pkg )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public void createPackage( byte[] content,java.lang.String contentType )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

   public void createOrReplacePackage( byte[] content,java.lang.String contentType )
      throws org.wfmc.wapi.WMWorkflowException, java.rmi.RemoteException;

}
