/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.worklist;

/**
 * Home interface for Participant.
 * @author ruth
 * @created 11. Dezember 2003
 */
public interface ParticipantHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Participant";
   public static final String JNDI_NAME="de/objectcode/canyon/ejb/worklist/Participant";

   public de.objectcode.canyon.api.worklist.Participant create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
