/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.worklist;

/**
 * Local home interface for Participant.
 * @author ruth
 * @created 11. Dezember 2003
 */
public interface ParticipantLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ParticipantLocal";
   public static final String JNDI_NAME="de/objectcode/canyon/ejb/worklist/ParticipantLocal";

   public de.objectcode.canyon.api.worklist.ParticipantLocal create()
      throws javax.ejb.CreateException;

}
