/*
 * Generated by XDoclet - Do not edit!
 */
package de.objectcode.canyon.api.worklist;

/**
 * Local home interface for Worklist.
 * @author junglas
 * @created 5. Dezember 2003
 */
public interface WorklistLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WorklistLocal";
   public static final String JNDI_NAME="de/objectcode/canyon/ejb/worklist/WorklistLocal";

   public de.objectcode.canyon.api.worklist.WorklistLocal create()
      throws javax.ejb.CreateException;

}
